Pandas

In [240]:
import pandas as pd
import numpy as np

In [241]:
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':10,'b':20,'c':30}

In [242]:
pd.Series(data=my_data)

0    10
1    20
2    30
dtype: int64

In [243]:
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [244]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [245]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [246]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [247]:
ser1=pd.Series([1,2,3,4],['USA','Germany','USSR','Japan'])

In [248]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [249]:
ser2=pd.Series([1,2,5,4],['USA','Germany','Italy','Japan'])

In [250]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [251]:
ser1['USA']

np.int64(1)

In [252]:
ser1 +ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

DataFrames in Pandas

In [253]:
from numpy.random import randn

In [254]:
np.random.seed(101)

In [255]:
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [256]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [257]:
arr=randn(5,4)
arr

array([[ 0.30266545,  1.69372293, -1.70608593, -1.15911942],
       [-0.13484072,  0.39052784,  0.16690464,  0.18450186],
       [ 0.80770591,  0.07295968,  0.63878701,  0.3296463 ],
       [-0.49710402, -0.7540697 , -0.9434064 ,  0.48475165],
       [-0.11677332,  1.9017548 ,  0.23812696,  1.99665229]])

In [258]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [259]:
type(df['W'])

pandas.core.series.Series

In [260]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [261]:
df.Y

A    0.907969
B   -0.848077
C    0.528813
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [262]:
df[['W','Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [263]:
df['new']=df['W']+df['Y']

In [264]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [265]:
df.drop('E',axis=0,inplace=True)

In [266]:
df.shape

(4, 5)

In [267]:
df.loc['A']

W      2.706850
X      0.628133
Y      0.907969
Z      0.503826
new    3.614819
Name: A, dtype: float64

In [268]:
df.iloc[2]

W     -2.018168
X      0.740122
Y      0.528813
Z     -0.589001
new   -1.489355
Name: C, dtype: float64

In [269]:
df.loc['B','Y']

np.float64(-0.8480769834036315)

In [270]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [271]:
df <0

       W      X      Y      Z    new
A  False  False  False  False  False
B  False   True   True  False   True
C   True  False  False   True   True
D  False   True   True  False   True

In [272]:
df[df['W']>0][['Y','X']]

          Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872

In [273]:
boolser= df['W']>0
result=df[boolser]
mycols=['Y','X']
result[mycols]

          Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872

In [274]:
df[(df['W']>0) | (df['Y']>1)]

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542

In [275]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542

In [276]:
df.reset_index()

  index         W         X         Y         Z       new
0     A  2.706850  0.628133  0.907969  0.503826  3.614819
1     B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
2     C -2.018168  0.740122  0.528813 -0.589001 -1.489355
3     D  0.188695 -0.758872 -0.933237  0.955057 -0.744542

In [277]:
newind = 'CA NY WY OR'.split()

In [278]:
newind

['CA', 'NY', 'WY', 'OR']

In [279]:
df['States']=newind

In [280]:
df

          W         X         Y         Z       new States
A  2.706850  0.628133  0.907969  0.503826  3.614819     CA
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959     NY
C -2.018168  0.740122  0.528813 -0.589001 -1.489355     WY
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542     OR

In [281]:
df.set_index('States')

               W         X         Y         Z       new
States
CA      2.706850  0.628133  0.907969  0.503826  3.614819
NY      0.651118 -0.319318 -0.848077  0.605965 -0.196959
WY     -2.018168  0.740122  0.528813 -0.589001 -1.489355
OR      0.188695 -0.758872 -0.933237  0.955057 -0.744542

In [282]:
import numpy as np
import pandas as pd

In [283]:
outside=['G1','G1','G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
hier_index=list(zip(outside,inside))
hier_index=pd.MultiIndex.from_tuples(hier_index)

In [284]:
inside

[1, 2, 3, 1, 2, 3]

In [285]:
list(zip(outside, inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [286]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [287]:
df=pd.DataFrame(randn(6,2),hier_index,['A','B'])

In [288]:
df

             A         B
G1 1 -0.993263  0.196800
   2 -1.136645  0.000366
   3  1.025984 -0.156598
G2 1 -0.031579  0.649826
   2  2.154846 -0.610259
   3 -0.755325 -0.346419

In [289]:
df.loc['G1']

          A         B
1 -0.993263  0.196800
2 -1.136645  0.000366
3  1.025984 -0.156598

In [290]:
df.loc['G1'].loc[1]

A   -0.993263
B    0.196800
Name: 1, dtype: float64

In [291]:
df.index.names=['Groups','Num']

In [292]:
df

                   A         B
Groups Num
G1     1   -0.993263  0.196800
       2   -1.136645  0.000366
       3    1.025984 -0.156598
G2     1   -0.031579  0.649826
       2    2.154846 -0.610259
       3   -0.755325 -0.346419

In [293]:
df.loc['G2'].loc[2]['B']

np.float64(-0.6102588558227414)

In [294]:
df.xs(1,level='Num')

               A         B
Groups
G1     -0.993263  0.196800
G2     -0.031579  0.649826

Pandas-Missing Data

In [295]:
d={'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}

In [296]:
df=pd.DataFrame(d)

In [297]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [298]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [299]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [300]:
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [301]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [302]:
df.fillna(value='Fill Value')

            A           B  C
0         1.0         5.0  1
1         2.0  Fill Value  2
2  Fill Value  Fill Value  3

In [303]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [304]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

Group by

In [305]:
data={
    'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
    'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
    'Sales':[200,120,340,124,243,350]
}

In [306]:
data

{'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
 'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
 'Sales': [200, 120, 340, 124, 243, 350]}

In [307]:
df=pd.DataFrame(data)

In [308]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [309]:
byComp=df.groupby('Company')

In [310]:
byComp['Sales'].mean()

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

In [311]:
byComp.sum()

             Person  Sales
Company
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [312]:
byComp['Sales'].std()

Company
FB       75.660426
GOOG     56.568542
MSFT    152.735065
Name: Sales, dtype: float64

In [313]:
byComp.sum().loc['FB']

Person    CarlSarah
Sales           593
Name: FB, dtype: object

In [314]:
df.groupby('Company').count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [315]:
df.groupby('Company').max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [316]:
df.groupby('Company').describe().transpose()['FB']

Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FB, dtype: float64

Pandas - Operations

In [317]:
df=pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})

In [318]:
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [319]:
df['col2'].unique()

array([444, 555, 666])

In [320]:
len(df['col2'].unique())

3

In [321]:
df['col2'].nunique()

3

In [322]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [323]:
df[df['col1']>2]

   col1  col2 col3
2     3   666  ghi
3     4   444  xyz

In [324]:
bool_data=df['col1']>2

In [325]:
def times2(x):
    return x*2

In [326]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [327]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [328]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [329]:
df['col2'].apply(lambda x: x*3)

0    1332
1    1665
2    1998
3    1332
Name: col2, dtype: int64

In [330]:
df.drop('col1',axis=1)

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [331]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [332]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [333]:
df.sort_values(by='col2')

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [334]:
df.isnull()

    col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [335]:
data={'A':['foo','foo','foo','bar','bar','bar'],
      'B':['one','one','two','two','one','one'],
      'C':['x','y','x','y','x','y'],
      'D':[1,3,2,5,4,1]}
df=pd.DataFrame(data)

In [336]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [337]:
df.pivot_table(values='D',index=['A','B'],columns=['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

Data input and Output

In [338]:
pd.read_csv('example.csv')

   id     name  value        date    status                   notes
0   1    Alice     10  2022-01-01    active          Initial record
1   2      Bob     20  2022-01-02    active  Follow-up not required
2   3  Charlie     30  2022-01-03  inactive                 On hold
3   4    David     40  2022-01-04    active             New account
4   5      Eva     50  2022-01-05  inactive         Requires review
5   6    Frank     60  2022-01-06    active           High priority

In [339]:
df.to_csv('My_output.csv',index=False)

In [340]:
pd.read_csv('My_output.csv')

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [341]:
from sqlalchemy import create_engine

In [342]:
engine=create_engine('sqlite:///:memory:')

In [343]:
df.to_sql('my_table',engine)

6

In [344]:
sql_df=pd.read_sql('my_table',con=engine)

Pandas Excercise

In [345]:
import pandas as pd

In [346]:
sal=pd.read_csv('Salaries.csv')

In [347]:
sal.head(6)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN

In [348]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

In [349]:
sal['BasePay'].mean()

np.float64(66325.4488404877)

In [350]:
sal['OvertimePay'].max()

np.float64(245131.88)

In [351]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [352]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [353]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].max()]['EmployeeName']

0    NATHANIEL FORD
Name: EmployeeName, dtype: object

In [354]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()]['EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: object

In [356]:
sal['BasePay'] = pd.to_numeric(sal['BasePay'], errors='coerce')
sal.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [357]:
sal['JobTitle'].nunique()

2159

In [358]:
sal['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [360]:
sum(sal[sal['Year']==2013]['JobTitle'].value_counts()==1)

202

In [361]:
sal['JobTitle'].apply(lambda x: 'chief' in x.lower()).sum()

np.int64(627)

In [362]:
sal['title_len']=sal['JobTitle'].apply(len)

In [363]:
sal[['JobTitle','title_len']]

                                              JobTitle  title_len
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY         46
1                      CAPTAIN III (POLICE DEPARTMENT)         31
2                      CAPTAIN III (POLICE DEPARTMENT)         31
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC         36
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)         44
...                                                ...        ...
148649                                       Custodian          9
148650                                    Not provided         12
148651                                    Not provided         12
148652                                    Not provided         12
148653                      Counselor, Log Cabin Ranch         26

[148654 rows x 2 columns]

In [364]:
sal[['title_len','TotalPayBenefits']].corr()

                  title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000